#!/bin/bash
# Quick deployment script

echo "Quick S3 Deployment for RunPod"
echo "=============================="
echo ""
echo "Since the Docker build is taking too long, here's what to do:"
echo ""
echo "1. Build the image locally without timeout:"
echo ""
echo "   cd runpod-multitalk"
echo "   docker build --platform linux/amd64 \\"
echo "     -t berrylands/multitalk-complete:v2.1.0-s3 \\"
echo "     -f Dockerfile.complete ."
echo ""
echo "2. Push to DockerHub:"
echo ""
echo "   docker push berrylands/multitalk-complete:v2.1.0-s3"
echo ""
echo "3. Update RunPod endpoint to use:"
echo ""
echo "   berrylands/multitalk-complete:v2.1.0-s3"
echo ""
echo "The image includes:"
echo "✅ S3 handler module (s3_handler.py)"
echo "✅ Updated handler with S3 support"
echo "✅ boto3 installed"
echo "✅ Build info for verification"
echo ""
echo "To verify S3 is working after deployment:"
echo "   python test_s3_integration.py"