#!/bin/bash

echo "🚀 Triggering V131 build via GitHub Actions..."
echo ""
echo "Manual steps to trigger the build:"
echo "1. Go to: https://github.com/berrylands/meigen-multitalk-runpod-serverless/actions"
echo "2. Click on 'Build and Push MultiTalk' workflow"
echo "3. Click 'Run workflow' dropdown"
echo "4. Keep branch as 'master'"
echo "5. In 'Version to build' field, enter: v131"
echo "6. Click the green 'Run workflow' button"
echo ""
echo "The build should take about 10-15 minutes."
echo ""
echo "Monitor the build at:"
echo "https://github.com/berrylands/meigen-multitalk-runpod-serverless/actions"
echo ""
echo "Once complete, check Docker Hub:"
echo "https://hub.docker.com/r/berrylands/multitalk-runpod/tags"