name: Build and Push MultiTalk

on:
  push:
    branches: [ master, main ]
    paths:
      - 'runpod-multitalk/Dockerfile.v*'
      - 'runpod-multitalk/handler_v*.py'
      - 'runpod-multitalk/multitalk_v*.py'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., v130-final)'
        required: false
        default: 'v130-final'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: jasonedge
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event.inputs.version }}" != "" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          # Default to v130-final
          VERSION="v130-final"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
        
        # Extract tag from version (e.g., v130-final -> v130)
        TAG=$(echo "$VERSION" | sed 's/-final//' | sed 's/-fixed//')
        echo "tag=$TAG" >> $GITHUB_OUTPUT
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./runpod-multitalk
        file: ./runpod-multitalk/Dockerfile.${{ steps.version.outputs.version }}
        platforms: linux/amd64
        push: true
        tags: |
          jasonedge/multitalk-runpod:${{ steps.version.outputs.tag }}
          jasonedge/multitalk-runpod:${{ steps.version.outputs.version }}
          jasonedge/multitalk-runpod:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILD_TIME=${{ github.event.repository.updated_at }}
          BUILD_ID=gh-${{ github.run_id }}
    
    - name: Update RunPod template
      if: success()
      run: |
        echo "✅ Docker image pushed successfully!"
        echo "📦 Image: jasonedge/multitalk-runpod:${{ steps.version.outputs.tag }}"
        echo ""
        echo "Template ID: 5y1gyg4n78kqwz"
        echo "New image: jasonedge/multitalk-runpod:${{ steps.version.outputs.tag }}"
        echo ""
        echo "To update the template:"
        echo "1. Go to RunPod dashboard"
        echo "2. Navigate to Templates"
        echo "3. Update the Docker image"
    
    - name: Create summary
      run: |
        echo "# MultiTalk Build Complete! 🎉" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Version: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tag:** ${{ steps.version.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** jasonedge/multitalk-runpod:${{ steps.version.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## RunPod Template" >> $GITHUB_STEP_SUMMARY
        echo "Template ID: \`5y1gyg4n78kqwz\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## V130 Final Features" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ PyTorch 2.1.0+cu121 (compatible with cog-MultiTalk)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Torchvision 0.16.0" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ NumPy 1.26.4 (avoiding NumPy 2.x issues)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ xformers 0.0.22" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ xfuser, scikit-image, and all dependencies" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Next Steps" >> $GITHUB_STEP_SUMMARY
        echo "1. Update RunPod template with new image" >> $GITHUB_STEP_SUMMARY
        echo "2. Test with S3 files (1.wav and multi1.png)" >> $GITHUB_STEP_SUMMARY